services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes: 
      - /mnt/data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prom:/etc/prometheus
      - /mnt/data/prom_data:/prometheus
    ports:
      - 9090:9090
    restart: always

  prometheus-pve-exporter:
    image: prompve/prometheus-pve-exporter
    volumes:
      - ./config/pve/pve.yml:/etc/prometheus/pve.yml
    ports:
      - 9221:9221
    container_name: prometheus-pve-exporter
    restart: always
  
  mktxp:
    container_name: mktxp
    image: ghcr.io/akpw/mktxp:latest
    user: root
    volumes:
      - ./config/mktxp/:/root/mktxp/
    restart: unless-stopped  
