global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']



  - job_name: 'Node Exporter'
    scrape_interval: 5s

    static_configs:
      - targets: ['192.168.88.1:9100']
        labels:
          instance: pve01-austin

  - job_name: 'telegraf'
    static_configs:
      - targets: ['192.168.88.1:9273']
        labels:
          instance: av-print01
  
  - job_name: 'mktxp'
    static_configs:
      - targets: ['mktxp:49090']

  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.88.1  # Proxmox VE node.
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-pve-exporter:9221  # PVE exporter.